/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Xhen Rii
 */
public class userLogin extends javax.swing.JFrame {

    /**
     * Creates new form userLogin
     */
    public userLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMtrEmpApp = new javax.swing.JLabel();
        lblUsrnm = new javax.swing.JLabel();
        lblPswrd = new javax.swing.JLabel();
        radioEmp = new javax.swing.JRadioButton();
        radioAdmin = new javax.swing.JRadioButton();
        txtUsrnm = new javax.swing.JTextField();
        txtPswrd = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMtrEmpApp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMtrEmpApp.setText("MotorPH Employee App");

        lblUsrnm.setText("Username:");

        lblPswrd.setText("Password:");

        radioEmp.setText("Employee");
        radioEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEmpActionPerformed(evt);
            }
        });

        radioAdmin.setText("Admin");

        btnLogin.setText("Log in");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(lblMtrEmpApp))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioEmp)
                                .addGap(35, 35, 35)
                                .addComponent(radioAdmin)
                                .addGap(29, 29, 29))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblPswrd)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblUsrnm)
                                        .addGap(15, 15, 15)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnLogin)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtUsrnm, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                        .addComponent(txtPswrd)))))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblMtrEmpApp)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioEmp)
                    .addComponent(radioAdmin))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsrnm)
                    .addComponent(txtUsrnm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPswrd)
                    .addComponent(txtPswrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btnLogin)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioEmpActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {
        String username = txtUsrnm.getText();
        String password = txtPswrd.getText();
        
        // Check if Employee radio is selected
        if (radioEmp.isSelected()) {
            if (username.equals("emp") && password.equals("emp1")) {
                // If correct credentials Employee Dashboard will open
                javax.swing.JOptionPane.showMessageDialog(this, "Welcome, Employee! Employee Dashboard will open here.");
                this.dispose();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Invalid Employee credentials!", "Inavlid Credentials", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
        // Check if Admin radio is selected
        else if (radioAdmin.isSelected()) {
            if (username.equals("admin") && password.equals("admin")) {
                // If correct credentials Admin Dashboard will open
                javax.swing.JOptionPane.showMessageDialog(this, "Welcome, Admin! Admin Dashboard will open here.");
                this.dispose();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Invalid Admin credentials!", "Inavlid Credentials", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
        // If no radio button is selected
        else {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a role (Employee or Admin)!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblMtrEmpApp;
    private javax.swing.JLabel lblPswrd;
    private javax.swing.JLabel lblUsrnm;
    private javax.swing.JRadioButton radioAdmin;
    private javax.swing.JRadioButton radioEmp;
    private javax.swing.JTextField txtPswrd;
    private javax.swing.JTextField txtUsrnm;
    // End of variables declaration//GEN-END:variables
}
